# Generated by Django 5.1.3 on 2024-11-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='category',
            field=models.CharField(choices=[('Flwr_plant', 'Flowering Plants'), ('non-Flowering_Plant', 'Non-Flowering Plants'), ('Tree', 'Tree'), ('Herb', 'Herb'), ('Shrub', 'Shrubs'), ('aquatic_plant', 'Aquatic Plant')], max_length=56),
        ),
    ]
